# Generated by Django 4.2.7 on 2024-11-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
